package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaTour generated by hbm2java
 */
@Entity
@Table(name = "categoria_tour", catalog = "turismo_bd")
public class CategoriaTour implements java.io.Serializable {

	private String idCategoria;
	private String nombre;
	private Set<Tour> tours = new HashSet<Tour>(0);

	public CategoriaTour() {
	}

	public CategoriaTour(String idCategoria, String nombre) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
	}

	public CategoriaTour(String idCategoria, String nombre, Set<Tour> tours) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.tours = tours;
	}

	@Id

	@Column(name = "id_categoria", unique = true, nullable = false, length = 45)
	public String getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(String idCategoria) {
		this.idCategoria = idCategoria;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaTour")
	public Set<Tour> getTours() {
		return this.tours;
	}

	public void setTours(Set<Tour> tours) {
		this.tours = tours;
	}

}
