package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaleriaLugar generated by hbm2java
 */
@Entity
@Table(name = "galeria_lugar", catalog = "turismo_bd")
public class GaleriaLugar implements java.io.Serializable {

	private int idGaleriaLugar;
	private MultimediaLugar multimediaLugar;
	private String nombre;
	private Date fechaCreacion;
	private Set<LugarTuristico> lugarTuristicos = new HashSet<LugarTuristico>(0);

	public GaleriaLugar() {
	}

	public GaleriaLugar(int idGaleriaLugar, MultimediaLugar multimediaLugar, String nombre, Date fechaCreacion) {
		this.idGaleriaLugar = idGaleriaLugar;
		this.multimediaLugar = multimediaLugar;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
	}

	public GaleriaLugar(int idGaleriaLugar, MultimediaLugar multimediaLugar, String nombre, Date fechaCreacion,
			Set<LugarTuristico> lugarTuristicos) {
		this.idGaleriaLugar = idGaleriaLugar;
		this.multimediaLugar = multimediaLugar;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.lugarTuristicos = lugarTuristicos;
	}

	@Id

	@Column(name = "id_galeria_lugar", unique = true, nullable = false)
	public int getIdGaleriaLugar() {
		return this.idGaleriaLugar;
	}

	public void setIdGaleriaLugar(int idGaleriaLugar) {
		this.idGaleriaLugar = idGaleriaLugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_multimedia", nullable = false)
	public MultimediaLugar getMultimediaLugar() {
		return this.multimediaLugar;
	}

	public void setMultimediaLugar(MultimediaLugar multimediaLugar) {
		this.multimediaLugar = multimediaLugar;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", nullable = false, length = 10)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "galeriaLugar")
	public Set<LugarTuristico> getLugarTuristicos() {
		return this.lugarTuristicos;
	}

	public void setLugarTuristicos(Set<LugarTuristico> lugarTuristicos) {
		this.lugarTuristicos = lugarTuristicos;
	}

}
