package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaleriaTour generated by hbm2java
 */
@Entity
@Table(name = "galeria_tour", catalog = "turismo_bd")
public class GaleriaTour implements java.io.Serializable {

	private String idGaleria;
	private MultimediaTour multimediaTour;
	private Tour tour;
	private String nombre;
	private Date fechaCreacion;

	public GaleriaTour() {
	}

	public GaleriaTour(String idGaleria, MultimediaTour multimediaTour, Tour tour, String nombre, Date fechaCreacion) {
		this.idGaleria = idGaleria;
		this.multimediaTour = multimediaTour;
		this.tour = tour;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
	}

	@Id

	@Column(name = "id_galeria", unique = true, nullable = false, length = 45)
	public String getIdGaleria() {
		return this.idGaleria;
	}

	public void setIdGaleria(String idGaleria) {
		this.idGaleria = idGaleria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_multimedia", nullable = false)
	public MultimediaTour getMultimediaTour() {
		return this.multimediaTour;
	}

	public void setMultimediaTour(MultimediaTour multimediaTour) {
		this.multimediaTour = multimediaTour;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tour", nullable = false)
	public Tour getTour() {
		return this.tour;
	}

	public void setTour(Tour tour) {
		this.tour = tour;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", nullable = false, length = 10)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

}
