package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LugarTuristico generated by hbm2java
 */
@Entity
@Table(name = "lugar_turistico", catalog = "turismo_bd")
public class LugarTuristico implements java.io.Serializable {

	private int idLugar;
	private GaleriaLugar galeriaLugar;
	private UserAgencia userAgencia;
	private String nombre;
	private byte[] imagen;
	private String descripcion;
	private String ubicacion;

	public LugarTuristico() {
	}

	public LugarTuristico(int idLugar, GaleriaLugar galeriaLugar, UserAgencia userAgencia, String nombre,
			String descripcion, String ubicacion) {
		this.idLugar = idLugar;
		this.galeriaLugar = galeriaLugar;
		this.userAgencia = userAgencia;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ubicacion = ubicacion;
	}

	public LugarTuristico(int idLugar, GaleriaLugar galeriaLugar, UserAgencia userAgencia, String nombre, byte[] imagen,
			String descripcion, String ubicacion) {
		this.idLugar = idLugar;
		this.galeriaLugar = galeriaLugar;
		this.userAgencia = userAgencia;
		this.nombre = nombre;
		this.imagen = imagen;
		this.descripcion = descripcion;
		this.ubicacion = ubicacion;
	}

	@Id

	@Column(name = "id_lugar", unique = true, nullable = false)
	public int getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(int idLugar) {
		this.idLugar = idLugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_galeria_lugar", nullable = false)
	public GaleriaLugar getGaleriaLugar() {
		return this.galeriaLugar;
	}

	public void setGaleriaLugar(GaleriaLugar galeriaLugar) {
		this.galeriaLugar = galeriaLugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta", nullable = false)
	public UserAgencia getUserAgencia() {
		return this.userAgencia;
	}

	public void setUserAgencia(UserAgencia userAgencia) {
		this.userAgencia = userAgencia;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@Column(name = "descripcion", nullable = false, length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ubicacion", nullable = false, length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

}
