package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MultimediaLugar generated by hbm2java
 */
@Entity
@Table(name = "multimedia_lugar", catalog = "turismo_bd")
public class MultimediaLugar implements java.io.Serializable {

	private int idMultimedia;
	private String ubicacion;
	private Set<GaleriaLugar> galeriaLugars = new HashSet<GaleriaLugar>(0);

	public MultimediaLugar() {
	}

	public MultimediaLugar(int idMultimedia, String ubicacion) {
		this.idMultimedia = idMultimedia;
		this.ubicacion = ubicacion;
	}

	public MultimediaLugar(int idMultimedia, String ubicacion, Set<GaleriaLugar> galeriaLugars) {
		this.idMultimedia = idMultimedia;
		this.ubicacion = ubicacion;
		this.galeriaLugars = galeriaLugars;
	}

	@Id

	@Column(name = "id_multimedia", unique = true, nullable = false)
	public int getIdMultimedia() {
		return this.idMultimedia;
	}

	public void setIdMultimedia(int idMultimedia) {
		this.idMultimedia = idMultimedia;
	}

	@Column(name = "ubicacion", nullable = false, length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimediaLugar")
	public Set<GaleriaLugar> getGaleriaLugars() {
		return this.galeriaLugars;
	}

	public void setGaleriaLugars(Set<GaleriaLugar> galeriaLugars) {
		this.galeriaLugars = galeriaLugars;
	}

}
