package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MultimediaTour generated by hbm2java
 */
@Entity
@Table(name = "multimedia_tour", catalog = "turismo_bd")
public class MultimediaTour implements java.io.Serializable {

	private String idMultimedia;
	private String ubicacion;
	private Set<GaleriaTour> galeriaTours = new HashSet<GaleriaTour>(0);

	public MultimediaTour() {
	}

	public MultimediaTour(String idMultimedia, String ubicacion) {
		this.idMultimedia = idMultimedia;
		this.ubicacion = ubicacion;
	}

	public MultimediaTour(String idMultimedia, String ubicacion, Set<GaleriaTour> galeriaTours) {
		this.idMultimedia = idMultimedia;
		this.ubicacion = ubicacion;
		this.galeriaTours = galeriaTours;
	}

	@Id

	@Column(name = "id_multimedia", unique = true, nullable = false, length = 45)
	public String getIdMultimedia() {
		return this.idMultimedia;
	}

	public void setIdMultimedia(String idMultimedia) {
		this.idMultimedia = idMultimedia;
	}

	@Column(name = "ubicacion", nullable = false, length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multimediaTour")
	public Set<GaleriaTour> getGaleriaTours() {
		return this.galeriaTours;
	}

	public void setGaleriaTours(Set<GaleriaTour> galeriaTours) {
		this.galeriaTours = galeriaTours;
	}

}
