package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RedSocial generated by hbm2java
 */
@Entity
@Table(name = "red_social", catalog = "turismo_bd")
public class RedSocial implements java.io.Serializable {

	private int idRedSocial;
	private TipoRedSocial tipoRedSocial;
	private UserAgencia userAgencia;
	private String enlace;

	public RedSocial() {
	}

	public RedSocial(int idRedSocial, TipoRedSocial tipoRedSocial, UserAgencia userAgencia, String enlace) {
		this.idRedSocial = idRedSocial;
		this.tipoRedSocial = tipoRedSocial;
		this.userAgencia = userAgencia;
		this.enlace = enlace;
	}

	@Id

	@Column(name = "id_red_social", unique = true, nullable = false)
	public int getIdRedSocial() {
		return this.idRedSocial;
	}

	public void setIdRedSocial(int idRedSocial) {
		this.idRedSocial = idRedSocial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_social", nullable = false)
	public TipoRedSocial getTipoRedSocial() {
		return this.tipoRedSocial;
	}

	public void setTipoRedSocial(TipoRedSocial tipoRedSocial) {
		this.tipoRedSocial = tipoRedSocial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta", nullable = false)
	public UserAgencia getUserAgencia() {
		return this.userAgencia;
	}

	public void setUserAgencia(UserAgencia userAgencia) {
		this.userAgencia = userAgencia;
	}

	@Column(name = "enlace", nullable = false, length = 45)
	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

}
