package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoRedSocial generated by hbm2java
 */
@Entity
@Table(name = "tipo_red_social", catalog = "turismo_bd")
public class TipoRedSocial implements java.io.Serializable {

	private int idTipoSocial;
	private String nombre;
	private String icono;
	private Set<RedSocial> redSocials = new HashSet<RedSocial>(0);

	public TipoRedSocial() {
	}

	public TipoRedSocial(int idTipoSocial, String nombre, String icono) {
		this.idTipoSocial = idTipoSocial;
		this.nombre = nombre;
		this.icono = icono;
	}

	public TipoRedSocial(int idTipoSocial, String nombre, String icono, Set<RedSocial> redSocials) {
		this.idTipoSocial = idTipoSocial;
		this.nombre = nombre;
		this.icono = icono;
		this.redSocials = redSocials;
	}

	@Id

	@Column(name = "id_tipo_social", unique = true, nullable = false)
	public int getIdTipoSocial() {
		return this.idTipoSocial;
	}

	public void setIdTipoSocial(int idTipoSocial) {
		this.idTipoSocial = idTipoSocial;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icono", nullable = false, length = 45)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoRedSocial")
	public Set<RedSocial> getRedSocials() {
		return this.redSocials;
	}

	public void setRedSocials(Set<RedSocial> redSocials) {
		this.redSocials = redSocials;
	}

}
