package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserCliente generated by hbm2java
 */
@Entity
@Table(name = "user_cliente", catalog = "turismo_bd")
public class UserCliente implements java.io.Serializable {

	private String cuenta;
	private Usuario usuario;
	private String edad;
	private String sexo;

	public UserCliente() {
	}

	public UserCliente(Usuario usuario) {
		this.usuario = usuario;
	}

	public UserCliente(Usuario usuario, String edad, String sexo) {
		this.usuario = usuario;
		this.edad = edad;
		this.sexo = sexo;
	}

	@GenericGenerator(name = "udaff.io.entities.UserClienteIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "udaff.io.entities.UserClienteIdGenerator")

	@Column(name = "cuenta", unique = true, nullable = false, length = 45)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "edad", length = 3)
	public String getEdad() {
		return this.edad;
	}

	public void setEdad(String edad) {
		this.edad = edad;
	}

	@Column(name = "sexo", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

}
