package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VredsocialId generated by hbm2java
 */
@Embeddable
public class VredsocialId implements java.io.Serializable {

	private int idTipoSocial;
	private String nombre;
	private String icono;

	public VredsocialId() {
	}

	public VredsocialId(int idTipoSocial, String nombre, String icono) {
		this.idTipoSocial = idTipoSocial;
		this.nombre = nombre;
		this.icono = icono;
	}

	@Column(name = "id_tipo_social", nullable = false)
	public int getIdTipoSocial() {
		return this.idTipoSocial;
	}

	public void setIdTipoSocial(int idTipoSocial) {
		this.idTipoSocial = idTipoSocial;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "icono", nullable = false, length = 45)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VredsocialId))
			return false;
		VredsocialId castOther = (VredsocialId) other;

		return (this.getIdTipoSocial() == castOther.getIdTipoSocial())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getIcono() == castOther.getIcono()) || (this.getIcono() != null
						&& castOther.getIcono() != null && this.getIcono().equals(castOther.getIcono())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTipoSocial();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getIcono() == null ? 0 : this.getIcono().hashCode());
		return result;
	}

}
