package udaff.io.entities;
// Generated 08-sep-2020 16:12:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vredsocial generated by hbm2java
 */
@Entity
@Table(name = "vredsocial", catalog = "turismo_bd")
public class Vredsocial implements java.io.Serializable {

	private VredsocialId id;

	public Vredsocial() {
	}

	public Vredsocial(VredsocialId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idTipoSocial", column = @Column(name = "id_tipo_social", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", nullable = false, length = 45)),
			@AttributeOverride(name = "icono", column = @Column(name = "icono", nullable = false, length = 45)) })
	public VredsocialId getId() {
		return this.id;
	}

	public void setId(VredsocialId id) {
		this.id = id;
	}

}
